package com.company.erp.batch.dto;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * Adds stock to a branch directly as a new batch, without a purchase order
 * (Batches > Add Batch). The batch number is generated by the system.
 * receivedDate defaults to today; it can be earlier (FIFO orders batches by
 * it) but never in the future.
 */
public record CreateBatchRequest(
        @NotNull UUID productId,
        @NotNull UUID branchId,
        @NotNull @Positive Integer quantity,
        @NotNull @PositiveOrZero BigDecimal costPrice,
        @PastOrPresent LocalDate receivedDate,
        @Size(max = 500) String note
) {
}
